const API_BASE=window.VAZ_API_BASE||'';
const TOKEN_KEY='vazPersonal.token';
const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
let token=localStorage.getItem(TOKEN_KEY)||'';
let me=null,view='home',clients=[],ops={clients:[],alerts:[],counts:{}},brand=null,selected=null,selectedOps=null,clientTab='summary',adminData={personals:[],counts:{}},authMode='login',pendingMsg='',aiDraft=false;

const goalNames={hypertrophy:'Hipertrofia',weight_loss:'Emagrecimento',recomp:'Recomposição corporal',strength:'Força',conditioning:'Condicionamento','5k':'5 km','10k':'10 km','21k':'Meia maratona','42k':'Maratona'};
const modeNames={hybrid:'Híbrido',strength:'Musculação',run:'Corrida'};
const muscleNames={chest:'Peitoral',back:'Costas',shoulders:'Ombros',quads:'Quadríceps',hamstrings:'Posteriores',glutes:'Glúteos',arms:'Braços',core:'Core',biceps:'Bíceps',triceps:'Tríceps',calves:'Panturrilhas'};
const dayNames=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>{if(!v)return '—';const d=new Date(String(v).length===10?`${v}T12:00:00`:v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR')};
const money=v=>v==null||v===''?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const initials=n=>String(n||'VP').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
function toast(msg){if(!toastEl)return;toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2600)}
function url(path,params={}){const u=new URL(path,API_BASE||location.origin);Object.entries(params).forEach(([k,v])=>v!=null&&u.searchParams.set(k,v));return u.toString()}
async function req(path,{method='GET',body=null,params=null,auth=true}={}){const headers={'Content-Type':'application/json'};if(auth&&token)headers.Authorization=`Bearer ${token}`;const r=await fetch(url(path,params||{}),{method,headers,body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(r.status===401&&auth){localStorage.removeItem(TOKEN_KEY);token='';me=null}if(!r.ok){const e=new Error(data.message||'Não foi possível concluir esta operação.');e.code=data.error;e.status=r.status;throw e}return data}
const authApi=(action,o={})=>req('/api/personal-auth',{...o,params:{...(o.params||{}),action}});
const vfApi=(action,o={})=>req('/api/vf',{...o,params:{...(o.params||{}),action}});
const opsApi=(action,o={})=>req('/api/personal-ops',{...o,params:{...(o.params||{}),action}});
const adminApi=(action,o={})=>req('/api/admin-v2',{...o,params:{...(o.params||{}),action}});

async function init(){
  if(!token){renderAuth();return}
  try{const d=await authApi('me');me=d.user;if(me.role==='admin'){view='admin-home';await loadAdmin()}else{view='home';await loadPersonal()}render()}catch(e){localStorage.removeItem(TOKEN_KEY);token='';me=null;renderAuth(e.message)}
}
async function loadPersonal(){const [a,b,c]=await Promise.all([vfApi('personal_clients'),opsApi('summary').catch(()=>({clients:[],alerts:[],counts:{}})),req('/api/branding').catch(()=>({branding:null}))]);clients=a.clients||[];ops=b;brand=c.branding||defaultBrand()}
async function loadAdmin(){const d=await adminApi('summary');adminData=d}
function defaultBrand(){return {systemName:'Vaz Fitness',primaryColor:'#f5c400',accentColor:'#151515',backgroundColor:'#ffffff',surfaceColor:'#ffffff',textColor:'#1c1c1c',logoUrl:null}}

function render(){if(!me)return renderAuth();app.innerHTML=me.role==='admin'?renderAdminShell():renderPersonalShell();bindCommon();me.role==='admin'?bindAdmin():bindPersonal()}
function renderAuth(message=''){
  me=null;const reg=authMode==='register';app.innerHTML=`<main class="vp-auth"><section class="vp-auth-card"><div class="vp-brand"><div class="vp-logo">VP</div><div><strong>Vaz Personal</strong><small>Central profissional</small></div></div><h1>${reg?'Criar conta':'Entrar'}</h1><p>${reg?'Cadastre-se para solicitar acesso à plataforma. A conta só será liberada após aprovação do administrador.':'Entre com seu e-mail. O administrador também pode usar o nome de usuário.'}</p>${pendingMsg?`<div class="vp-pending"><strong>Solicitação enviada</strong><p>${safe(pendingMsg)}</p></div>`:''}${message?`<div class="vp-alert danger"><div><strong>${safe(message)}</strong></div></div>`:''}<form id="authForm" class="vp-auth-form">${reg?'<input name="name" placeholder="Nome completo" required maxlength="80">':''}<input name="identifier" placeholder="${reg?'E-mail':'E-mail ou usuário'}" ${reg?'type="email"':''} required><input name="password" type="password" placeholder="Senha" minlength="8" required><button class="vp-btn primary">${reg?'Enviar solicitação':'Entrar'}</button></form><div class="vp-auth-switch">${reg?'Já possui conta?':'Ainda não possui conta?'} <button class="vp-link" id="authSwitch">${reg?'Entrar':'Solicitar acesso'}</button></div></section></main>`;
  document.getElementById('authSwitch').onclick=()=>{authMode=reg?'login':'register';pendingMsg='';renderAuth()};
  document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{if(reg){const d=await authApi('register',{method:'POST',body:{name:fd.get('name'),email:fd.get('identifier'),password:fd.get('password')},auth:false});pendingMsg=`Seu cadastro ${d.user?.publicCode||''} está aguardando aprovação. Você poderá entrar depois que o administrador liberar seu perfil.`;authMode='login';renderAuth()}else{const d=await authApi('login',{method:'POST',body:{identifier:fd.get('identifier'),password:fd.get('password')},auth:false});token=d.token;localStorage.setItem(TOKEN_KEY,token);me=d.user;if(me.role==='admin'){view='admin-home';await loadAdmin()}else{view='home';await loadPersonal()}if(me.mustChangePassword)view='settings';render()}}catch(err){if(err.code==='approval_pending')pendingMsg=err.message;renderAuth(err.code==='approval_pending'?'':err.message)}};
}

function personalNav(){return [{id:'home',ico:'⌂',label:'Início',sub:'visão geral'},{id:'students',ico:'◎',label:'Alunos',sub:'carteira'},{id:'billing',ico:'◫',label:'Mensalidades',sub:'financeiro'},{id:'brand',ico:'✦',label:'Identidade',sub:'sua marca'},{id:'settings',ico:'⚙',label:'Configurações',sub:'conta e segurança'}]}
function adminNav(){return [{id:'admin-home',ico:'⌂',label:'Painel',sub:'plataforma'},{id:'approvals',ico:'✓',label:'Aprovações',sub:'novos personals'},{id:'personals',ico:'◎',label:'Personals',sub:'ativos e bloqueios'},{id:'admin-billing',ico:'◫',label:'Cobranças',sub:'vencimentos'},{id:'settings',ico:'⚙',label:'Configurações',sub:'conta admin'}]}
function navHtml(items,mobile=false){return items.map(n=>`<button data-view="${n.id}" class="${view===n.id?'active':''}">${mobile?`<span class="ico">${n.ico}</span>${n.label}`:`<span class="ico">${n.ico}</span><span><b>${n.label}</b><small>${n.sub}</small></span>`}</button>`).join('')}
function topHtml(admin=false){return `<header class="vp-top"><div class="vp-brand"><div class="vp-logo">${admin?'A':'VP'}</div><div><strong>${admin?'Admin Vaz':'Vaz Personal'}</strong><small>${admin?'Controle da plataforma':'Gestão profissional'}</small></div></div><button class="vp-btn ghost" data-view="settings">${initials(me.name)}</button></header>`}
function renderPersonalShell(){const items=personalNav();return `<div class="vp-app">${topHtml(false)}<div class="vp-layout"><aside class="vp-side"><nav class="vp-nav">${navHtml(items)}</nav></aside><main class="vp-main">${selected?renderClient():renderPersonalView()}</main></div><nav class="vp-mobile-nav">${navHtml(items,true)}</nav></div>`}
function renderAdminShell(){const items=adminNav();return `<div class="vp-app">${topHtml(true)}<div class="vp-layout"><aside class="vp-side"><nav class="vp-nav">${navHtml(items)}</nav></aside><main class="vp-main">${renderAdminView()}</main></div><nav class="vp-mobile-nav">${navHtml(items,true)}</nav></div>`}
function pageHead(title,sub,actions=''){return `<div class="vp-page-head"><div><h1>${safe(title)}</h1><p>${safe(sub)}</p></div><div class="vp-actions">${actions}</div></div>`}
function badge(label,type='info'){return `<span class="vp-badge ${type}">${safe(label)}</span>`}
function statusBadge(s){return s==='approved'?badge('Ativo','ok'):s==='suspended'?badge('Suspenso','danger'):badge('Aguardando','warn')}

function renderPersonalView(){if(view==='students')return renderStudents();if(view==='billing')return renderBilling();if(view==='brand')return renderBrand();if(view==='settings')return renderSettings();return renderHome()}
function renderHome(){const active=clients.filter(x=>x.status==='approved').length,pending=clients.filter(x=>x.status==='pending').length;return `${pageHead('Bom dia, '+(me.name?.split(' ')[0]||'Personal'),'O que precisa da sua atenção hoje?')}<section class="vp-grid four"><div class="vp-card compact vp-stat"><span>Alunos</span><strong>${clients.length}</strong></div><div class="vp-card compact vp-stat"><span>Ativos</span><strong>${active}</strong></div><div class="vp-card compact vp-stat"><span>Treinos a revisar</span><strong>${ops.counts?.cycleReview||0}</strong></div><div class="vp-card compact vp-stat"><span>Mensalidades pendentes</span><strong>${ops.counts?.billingPending||0}</strong></div></section><section class="vp-grid two vp-section"><div class="vp-card"><div class="vp-page-head"><div><h2>Atenções</h2><p>Treinos, pagamentos e liberações.</p></div></div>${pending?`<div class="vp-alert warn"><span>👤</span><div><strong>${pending} aluno(s) aguardando liberação</strong><small>Revise cadastro e plano antes de liberar.</small></div></div>`:''}${(ops.alerts||[]).slice(0,6).map(a=>`<button class="vp-alert ${a.severity==='danger'?'danger':'warn'}" data-open="${a.athleteId}" style="width:100%;text-align:left;border-style:solid"><span>${a.kind==='billing'?'💳':'⏱'}</span><div><strong>${safe(a.name)}</strong><small>${safe(a.message)}</small></div></button>`).join('')||(!pending?'<div class="vp-empty">Nenhuma pendência importante agora.</div>':'')}</div><div class="vp-card"><div class="vp-page-head"><div><h2>Ações rápidas</h2><p>Atalhos do dia a dia.</p></div></div><div class="vp-grid two"><button class="vp-btn primary" data-view="students">+ Vincular aluno</button><button class="vp-btn ghost" data-view="billing">Mensalidades</button><button class="vp-btn ghost" data-view="brand">Personalizar sistema</button><button class="vp-btn dark" id="refreshPersonal">Atualizar dados</button></div></div></section><section class="vp-card vp-section"><div class="vp-page-head"><div><h2>Alunos recentes</h2><p>Acesse treino, evolução e gestão.</p></div><button class="vp-btn ghost" data-view="students">Ver todos</button></div>${clientRows(clients.slice(0,6))}</section>`}
function clientRows(list){if(!list.length)return '<div class="vp-empty">Nenhum aluno vinculado.</div>';return list.map(c=>`<div class="vp-row"><div class="vp-avatar">${initials(c.name)}</div><div class="vp-row-main"><strong>${safe(c.name)}</strong><small><span class="vp-code">${safe(c.publicCode)}</span> • ${safe(goalNames[c.summary?.goal]||c.summary?.goal||'perfil')}</small></div>${statusBadge(c.status)}<button class="vp-btn ghost" data-open="${c.id}">Abrir</button></div>`).join('')}
function renderStudents(){return `${pageHead('Meus alunos','Carteira completa e solicitações.',`<button class="vp-btn primary" id="claimBtn">+ Código ID</button>`)}<section class="vp-card">${clientRows(clients)}</section>`}
function renderBilling(){const list=ops.clients||[];return `${pageHead('Mensalidades','Controle financeiro dos seus alunos.')}<section class="vp-grid three"><div class="vp-card compact vp-stat"><span>Configuradas</span><strong>${list.filter(x=>x.billing?.configured).length}</strong></div><div class="vp-card compact vp-stat"><span>Pendentes</span><strong>${list.filter(x=>x.billing?.status==='pending').length}</strong></div><div class="vp-card compact vp-stat"><span>Sem vencimento</span><strong>${list.filter(x=>!x.billing?.configured).length}</strong></div></section><section class="vp-card vp-section">${list.length?list.map(x=>`<div class="vp-row"><div class="vp-avatar">${initials(x.name)}</div><div class="vp-row-main"><strong>${safe(x.name)}</strong><small>${x.billing?.configured?`Vence ${fmtDate(x.billing.nextDueDate)} • ${money(x.billing.amount)}`:'Mensalidade não configurada'}</small></div>${x.billing?.status==='pending'?badge('Pendente','danger'):x.billing?.configured?badge('Em dia','ok'):badge('Configurar','warn')}<button class="vp-btn ghost" data-open="${x.id}" data-tab-target="management">Gerenciar</button></div>`).join(''):'<div class="vp-empty">Nenhum aluno para exibir.</div>'}</section>`}
function renderBrand(){const b=brand||defaultBrand();return `${pageHead('Identidade do sistema','Crie a experiência que seus alunos verão.')}<section class="vp-grid two"><form class="vp-card" id="brandForm"><h2>Sua marca</h2><p>Nome, cores e logo são sincronizados com os alunos liberados.</p><div class="vp-form-grid"><div class="vp-field"><label>Nome do sistema</label><input name="systemName" value="${safe(b.systemName)}" maxlength="50"></div><div class="vp-field"><label>Logo (URL HTTPS)</label><input name="logoUrl" value="${safe(b.logoUrl||'')}" placeholder="https://..."></div><div class="vp-field"><label>Cor principal</label><input name="primaryColor" type="color" value="${safe(b.primaryColor)}"></div><div class="vp-field"><label>Contraste</label><input name="accentColor" type="color" value="${safe(b.accentColor)}"></div><div class="vp-field"><label>Fundo</label><input name="backgroundColor" type="color" value="${safe(b.backgroundColor)}"></div><div class="vp-field"><label>Cards</label><input name="surfaceColor" type="color" value="${safe(b.surfaceColor)}"></div><div class="vp-field"><label>Texto</label><input name="textColor" type="color" value="${safe(b.textColor)}"></div></div><div class="vp-actions" style="margin-top:12px"><button class="vp-btn primary">Salvar identidade</button></div></form><div class="vp-card"><h2>Prévia no celular</h2><p>A prévia agora ocupa a largura correta e simula o app do aluno.</p><div class="vp-phone-preview-wrap"><div class="vp-phone" id="brandPreview" style="--preview-bg:${safe(b.backgroundColor)};--preview-surface:${safe(b.surfaceColor)};--preview-primary:${safe(b.primaryColor)};--preview-text:${safe(b.textColor)}"><div class="vp-phone-bar"></div><div class="vp-phone-screen"><div class="vp-phone-brand"><div class="vp-phone-brandmark">${b.logoUrl?'◎':'VF'}</div><div><strong id="previewName">${safe(b.systemName)}</strong><small style="display:block;opacity:.6">Seu treino de hoje</small></div></div><div class="vp-phone-card"><small style="opacity:.6">TREINO DE HOJE</small><h3 style="margin:5px 0">Peito + tríceps</h3><p style="margin:0;opacity:.65">6 exercícios • 55 min</p><div class="vp-phone-button">Iniciar treino</div></div><div class="vp-phone-card"><small style="opacity:.6">EVOLUÇÃO</small><h3 style="margin:5px 0">Consistência 82%</h3><p style="margin:0;opacity:.65">Você está evoluindo bem.</p></div></div></div></div></div></section>`}
function renderSettings(){return `${pageHead('Configurações','Cadastro, alunos, segurança e sessão.')} ${me.mustChangePassword?`<div class="vp-alert danger"><span>🔐</span><div><strong>Troque sua senha temporária</strong><small>Esta alteração é obrigatória para proteger o acesso administrativo.</small></div></div>`:''}<section class="vp-grid two vp-section"><form class="vp-card" id="profileForm"><h2>Meu cadastro</h2><p>Informações da sua conta.</p><div class="vp-field"><label>Nome</label><input name="name" value="${safe(me.name)}"></div><div class="vp-field" style="margin-top:8px"><label>E-mail</label><input name="email" type="email" value="${safe(me.email)}"></div>${me.username?`<div class="vp-kv"><span>Usuário</span><strong>${safe(me.username)}</strong></div>`:''}<div class="vp-kv"><span>Código</span><strong class="vp-code">${safe(me.publicCode)}</strong></div><button class="vp-btn primary" style="margin-top:10px">Salvar cadastro</button></form><div class="vp-card"><h2>Gestão</h2><div class="vp-settings-list">${me.role==='personal'?`<button class="vp-settings-item" data-view="students" style="border-left:0;border-right:0;border-bottom:0;background:none;text-align:left"><span class="ico">◎</span><div><strong>Gestão de alunos</strong><small>Carteira, planos e acessos</small></div><span>›</span></button><button class="vp-settings-item" data-view="billing" style="border-left:0;border-right:0;border-bottom:0;background:none;text-align:left"><span class="ico">◫</span><div><strong>Mensalidades</strong><small>Pagamentos dos alunos</small></div><span>›</span></button><button class="vp-settings-item" data-view="brand" style="border-left:0;border-right:0;border-bottom:0;background:none;text-align:left"><span class="ico">✦</span><div><strong>Identidade do sistema</strong><small>Nome, cores e logo</small></div><span>›</span></button>`:`<button class="vp-settings-item" data-view="personals" style="border-left:0;border-right:0;border-bottom:0;background:none;text-align:left"><span class="ico">◎</span><div><strong>Gerenciar personals</strong><small>Aprovações e bloqueios</small></div><span>›</span></button>`}</div></div></section><section class="vp-grid two vp-section"><form class="vp-card" id="passwordForm"><h2>Alterar senha</h2><div class="vp-field"><label>Senha atual</label><input name="current" type="password" required></div><div class="vp-field" style="margin-top:8px"><label>Nova senha</label><input name="next" type="password" minlength="8" required></div><button class="vp-btn dark" style="margin-top:10px">Alterar senha</button></form><div class="vp-card"><h2>Sessão</h2><p>O botão de saída fica somente aqui, longe das ações rotineiras.</p><button class="vp-btn danger" id="logoutBtn">Sair da conta</button></div></section>`}

async function openClient(id,tab='summary'){try{const [a,b]=await Promise.all([vfApi('personal_client',{params:{athleteId:id}}),opsApi('client',{params:{athleteId:id}})]);selected=a;selectedOps=b;clientTab=tab;view='students';render()}catch(e){toast(e.message)}}
function renderClient(){const a=selected.athlete,st=selected.state||{},p=st.profile||{};return `${pageHead(a.name,`${modeNames[p.mode]||'Perfil'} • ${goalNames[p.goal]||p.goal||'Objetivo não informado'}`,`<button class="vp-btn ghost" id="backClients">← Alunos</button>`)}<div class="vp-tabs">${[['summary','Resumo'],['plan','Plano'],['evolution','Evolução'],['management','Gestão'],['access','Acesso']].map(([id,l])=>`<button class="vp-tab ${clientTab===id?'active':''}" data-client-tab="${id}">${l}</button>`).join('')}</div>${clientTab==='plan'?renderClientPlan():clientTab==='evolution'?renderClientEvolution():clientTab==='management'?renderClientManagement():clientTab==='access'?renderClientAccess():renderClientSummary()}`}
function renderClientSummary(){const st=selected.state||{},p=st.profile||{},sessions=st.sessions||[],runs=st.runSessions||[],body=st.bodyMeasurements||[],weight=body.at(-1)?.weight||p.weight||'—';return `<section class="vp-grid four"><div class="vp-card compact vp-stat"><span>Peso</span><strong>${weight==='—'?'—':`${weight} kg`}</strong></div><div class="vp-card compact vp-stat"><span>Musculação</span><strong>${sessions.length}</strong></div><div class="vp-card compact vp-stat"><span>Corridas</span><strong>${runs.length}</strong></div><div class="vp-card compact vp-stat"><span>Status</span><strong style="font-size:14px">${selected.athlete.status==='approved'?'Ativo':selected.athlete.status==='suspended'?'Suspenso':'Aguardando'}</strong></div></section><section class="vp-grid two vp-section"><div class="vp-card"><h2>Perfil</h2>${[['Idade',p.age?`${p.age} anos`:'—'],['Altura',p.height?`${p.height} cm`:'—'],['Modalidade',modeNames[p.mode]||'—'],['Objetivo',goalNames[p.goal]||p.goal||'—'],['Dias/semana',p.days||'—'],['Prioridade',muscleNames[p.priorityMuscle]||p.priorityMuscle||'—']].map(([k,v])=>`<div class="vp-kv"><span>${k}</span><strong>${safe(v)}</strong></div>`).join('')}</div><div class="vp-card"><div class="vp-page-head"><div><h2>AION para o personal</h2><p>Análise dos dados recentes.</p></div><button class="vp-btn dark" id="analyzeClient">Analisar</button></div><div id="aiBox" class="vp-alert warn"><div><strong>AION IA</strong><small>Use a análise como apoio à sua decisão profissional.</small></div></div></div></section>`}
function renderClientPlan(){const plan=Array.isArray(selected.plan?.plan)?selected.plan.plan:[];return `<section class="vp-card"><div class="vp-page-head"><div><h2>Plano de treino</h2><p>Versão ${selected.plan?.plan_version||0}${aiDraft?' • rascunho gerado pela AION':''}</p></div><div class="vp-actions"><button class="vp-btn ghost" id="addDay">+ Dia</button><button class="vp-btn primary" id="savePlan">Salvar</button></div></div><div id="planDays">${plan.map((d,i)=>renderPlanDay(d,i)).join('')||'<div class="vp-empty">Nenhum treino cadastrado.</div>'}</div><div class="vp-field" style="margin-top:10px"><label>Orientações do personal</label><textarea id="planNotes" rows="3">${safe(selected.plan?.notes||'')}</textarea></div></section>`}
function renderPlanDay(d,i){const run=d.type==='run';return `<div class="vp-card compact" data-plan-day data-index="${i}" data-id="${safe(d.id||'')}" style="margin-top:9px;background:#fafaf8"><div class="vp-form-grid"><div class="vp-field"><label>Dia</label><select data-day="day">${dayNames.map((x,idx)=>`<option value="${idx}" ${Number(d.day)===idx?'selected':''}>${x}</option>`).join('')}</select></div><div class="vp-field"><label>Tipo</label><select data-day="type"><option value="strength" ${!run?'selected':''}>Musculação</option><option value="run" ${run?'selected':''}>Corrida</option></select></div><div class="vp-field"><label>Nome</label><input data-day="name" value="${safe(d.name||'Treino')}"></div><div class="vp-field"><label>Duração (min)</label><input data-day="duration" type="number" value="${Number(d.duration)||60}"></div></div>${run?`<div class="vp-form-grid" style="margin-top:8px"><div class="vp-field"><label>Pace</label><input data-day="pace" value="${safe(d.pace||'')}"></div><div class="vp-field"><label>Intensidade</label><input data-day="intensity" value="${safe(d.intensity||'Leve')}"></div></div>`:`<div style="margin-top:8px">${(d.exercises||[]).map((e,j)=>renderExercise(e,i,j)).join('')}<button class="vp-btn ghost" data-add-ex="${i}" style="margin-top:6px">+ Exercício</button></div>`}<div class="vp-actions" style="margin-top:8px"><button class="vp-btn danger" data-remove-day="${i}">Excluir dia</button></div></div>`}
function renderExercise(e,di,ei){return `<div class="vp-card compact" data-ex data-di="${di}" data-ei="${ei}" data-id="${safe(e.id||'')}" style="margin-top:6px"><div class="vp-form-grid"><div class="vp-field"><label>Exercício</label><input data-exf="name" value="${safe(e.name||'Exercício')}"></div><div class="vp-field"><label>Músculo</label><select data-exf="muscle">${Object.entries(muscleNames).map(([v,l])=>`<option value="${v}" ${e.muscle===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="vp-field"><label>Séries</label><input data-exf="sets" type="number" min="1" value="${Number(e.sets)||3}"></div><div class="vp-field"><label>Repetições</label><input data-exf="reps" value="${safe(e.reps||'8-12')}"></div><div class="vp-field"><label>Carga (kg)</label><input data-exf="load" type="number" step="0.5" value="${Number(e.load)||0}"></div><div class="vp-field"><label>Descanso (s)</label><input data-exf="rest" type="number" value="${Number(e.rest)||60}"></div></div><button class="vp-btn danger" data-remove-ex="${di}:${ei}" style="margin-top:6px">Remover</button></div>`}
function collectPlan(){return [...document.querySelectorAll('[data-plan-day]')].map((el,i)=>{const type=el.querySelector('[data-day="type"]').value,b={id:el.dataset.id||`vp-${Date.now()}-${i}`,type,name:el.querySelector('[data-day="name"]').value.trim()||'Treino',day:+el.querySelector('[data-day="day"]').value,duration:+el.querySelector('[data-day="duration"]').value||60,status:'pending'};if(type==='run'){b.pace=el.querySelector('[data-day="pace"]')?.value||'';b.intensity=el.querySelector('[data-day="intensity"]')?.value||'Leve'}else b.exercises=[...el.querySelectorAll('[data-ex]')].map((r,j)=>({id:r.dataset.id||`custom-${Date.now()}-${i}-${j}`,name:r.querySelector('[data-exf="name"]').value.trim()||'Exercício',muscle:r.querySelector('[data-exf="muscle"]').value,secondary:[],sets:+r.querySelector('[data-exf="sets"]').value||3,reps:r.querySelector('[data-exf="reps"]').value||'8-12',load:+r.querySelector('[data-exf="load"]').value||0,rest:+r.querySelector('[data-exf="rest"]').value||60,icon:'🏋️',priority:false}));return b})}
function mutatePlan(fn){const p=JSON.parse(JSON.stringify(selected.plan?.plan||[]));fn(p);selected.plan={...(selected.plan||{}),plan:p};render()}
function renderClientEvolution(){const st=selected.state||{},body=st.bodyMeasurements||[],runs=st.runSessions||[],sessions=st.sessions||[],m=(runs.reduce((a,r)=>a+Number(r.distance||0),0)).toFixed(1),vol=Math.max(0,...sessions.map(s=>Number(s.volume)||0));return `<section class="vp-grid four"><div class="vp-card compact vp-stat"><span>Treinos</span><strong>${sessions.length+runs.length}</strong></div><div class="vp-card compact vp-stat"><span>Km corridos</span><strong>${m}</strong></div><div class="vp-card compact vp-stat"><span>Maior volume</span><strong>${Math.round(vol).toLocaleString('pt-BR')}</strong></div><div class="vp-card compact vp-stat"><span>Peso atual</span><strong>${body.at(-1)?.weight?`${body.at(-1).weight} kg`:'—'}</strong></div></section><section class="vp-card vp-section"><h2>Histórico corporal</h2>${body.length?body.slice(-8).reverse().map(x=>`<div class="vp-row"><div class="vp-row-main"><strong>${x.weight?`${x.weight} kg`:'Registro corporal'}</strong><small>${fmtDate(x.date)}${x.waist?` • cintura ${x.waist} cm`:''}${x.bodyFat?` • gordura ${x.bodyFat}%`:''}</small></div></div>`).join(''):'<div class="vp-empty">Ainda não há medidas suficientes.</div>'}</section>`}
function renderClientManagement(){const c=selectedOps?.cycle||{},b=selectedOps?.billing||{},payments=selectedOps?.payments||[];return `<section class="vp-grid two"><div class="vp-card"><h2>Ciclo de treino</h2><p>Defina a duração e renove com apoio da AION.</p><div class="vp-form-grid"><div class="vp-field"><label>Duração</label><select id="cycleDays">${[30,45,60,90].map(x=>`<option value="${x}" ${Number(c.days||30)===x?'selected':''}>${x} dias</option>`).join('')}</select></div><div class="vp-field"><label>Vencimento</label><input value="${c.endsAt?fmtDate(c.endsAt):'Não iniciado'}" disabled></div></div><div style="margin-top:9px">${c.status==='expired'?badge('Treino vencido','danger'):c.status==='due_soon'?badge(`Vence em ${Math.max(0,c.daysLeft)} dias`,'warn'):c.status==='active'?badge('Ciclo ativo','ok'):badge('Ciclo não iniciado','info')}</div><div class="vp-actions" style="margin-top:10px"><button class="vp-btn ghost" id="startCycle">${c.status==='not_started'?'Iniciar ciclo':'Reiniciar ciclo'}</button><button class="vp-btn dark" id="suggestPlan">✦ Gerar novo treino com AION</button><button class="vp-btn primary" id="releaseCycle">Salvar e liberar novo ciclo</button></div></div><div class="vp-card"><h2>Mensalidade</h2><p>O sistema avisa; o bloqueio continua sob sua decisão.</p><form id="studentBillingForm"><div class="vp-form-grid"><div class="vp-field"><label>Valor</label><input name="amount" type="number" step="0.01" value="${b.amount??''}" placeholder="Opcional"></div><div class="vp-field"><label>Próximo vencimento</label><input name="dueDate" type="date" value="${safe(b.nextDueDate||'')}" required></div></div><div class="vp-field" style="margin-top:8px"><label>Observação</label><input name="notes" value="${safe(selectedOps?.billingNotes||'')}"></div><button class="vp-btn primary" style="margin-top:9px">Salvar cobrança</button></form><div class="vp-actions" style="margin-top:9px"><button class="vp-btn ok" id="studentPaid">Marcar pago</button><button class="vp-btn danger" id="studentPending">Marcar pendente</button></div></div></section><section class="vp-card vp-section"><h2>Histórico de pagamentos</h2>${payments.length?payments.map(x=>`<div class="vp-row"><div class="vp-row-main"><strong>${fmtDate(x.due_date)} • ${money(x.amount)}</strong><small>${x.status==='paid'?`Pago ${fmtDate(x.paid_at)}`:'Pendente'}</small></div>${x.status==='paid'?badge('Pago','ok'):badge('Pendente','danger')}</div>`).join(''):'<div class="vp-empty">Sem histórico registrado.</div>'}</section>`}
function renderClientAccess(){const s=selected.athlete.status;return `<section class="vp-card"><h2>Controle de acesso</h2><p>${s==='approved'?'O aluno pode acessar o app e receber atualizações do plano.':s==='suspended'?'O acesso do aluno está bloqueado.':'O aluno ainda aguarda sua avaliação e liberação.'}</p><div class="vp-actions">${s==='pending'?'<button class="vp-btn ok" data-access="approve">Liberar treino</button>':s==='suspended'?'<button class="vp-btn ok" data-access="reactivate">Reativar acesso</button>':'<button class="vp-btn danger" data-access="suspend">Bloquear aluno</button>'}</div><div class="vp-alert danger" style="margin-top:12px"><div><strong>Quando bloqueado</strong><small>O aluno verá: “Não foi possível entrar. Contate seu personal.”</small></div></div></section>`}

function renderAdminView(){if(view==='approvals')return renderApprovals();if(view==='personals')return renderPersonals();if(view==='admin-billing')return renderAdminBilling();if(view==='settings')return renderSettings();return renderAdminHome()}
function renderAdminHome(){const c=adminData.counts||{},pending=(adminData.personals||[]).filter(p=>p.accountStatus==='pending');return `${pageHead('Administração','Aprovações, contas e pagamentos da plataforma.')}<section class="vp-admin-hero"><h2 style="margin:0">Controle Vaz Personal</h2><p>Novos profissionais só entram após sua aprovação.</p></section><section class="vp-grid four vp-section"><div class="vp-card compact vp-stat"><span>Aguardando</span><strong>${c.pending||0}</strong></div><div class="vp-card compact vp-stat"><span>Ativos</span><strong>${c.active||0}</strong></div><div class="vp-card compact vp-stat"><span>Suspensos</span><strong>${c.suspended||0}</strong></div><div class="vp-card compact vp-stat"><span>Pagamentos pendentes</span><strong>${c.paymentPending||0}</strong></div></section><section class="vp-card vp-section"><div class="vp-page-head"><div><h2>Solicitações de aprovação</h2><p>Analise antes de liberar o uso do app.</p></div><button class="vp-btn ghost" data-view="approvals">Ver todas</button></div>${adminRows(pending.slice(0,6),'approval')}</section>`}
function adminRows(list,context='manage'){if(!list.length)return '<div class="vp-empty">Nenhum personal nesta categoria.</div>';return list.map(p=>`<div class="vp-row"><div class="vp-avatar">${initials(p.name)}</div><div class="vp-row-main"><strong>${safe(p.name)}</strong><small>${safe(p.email)} • ${p.athleteCount} aluno(s)</small></div>${p.accountStatus==='pending'?badge('Aguardando','warn'):p.accountStatus==='suspended'?badge('Suspenso','danger'):badge('Ativo','ok')}${context==='approval'?`<button class="vp-btn ok" data-admin-status="approve" data-personal="${p.id}">Aprovar</button>`:`<button class="vp-btn ghost" data-admin-manage="${p.id}">Gerenciar</button>`}</div>`).join('')}
function renderApprovals(){const list=(adminData.personals||[]).filter(p=>p.accountStatus==='pending');return `${pageHead('Aprovar personals','Novos cadastros aguardando sua decisão.')}<section class="vp-card">${adminRows(list,'approval')}</section>`}
function renderPersonals(){const list=adminData.personals||[];return `${pageHead('Personals','Gerencie profissionais ativos e suspensos.')}<section class="vp-card">${adminRows(list)}</section>`}
function renderAdminBilling(){const list=adminData.personals||[];return `${pageHead('Cobranças dos personals','Vencimentos, pagamento pendente e bloqueio.')}<section class="vp-grid three"><div class="vp-card compact vp-stat"><span>Com vencimento</span><strong>${list.filter(p=>p.subscription?.nextDueDate).length}</strong></div><div class="vp-card compact vp-stat"><span>Pendentes</span><strong>${list.filter(p=>p.subscription?.paymentStatus==='pending').length}</strong></div><div class="vp-card compact vp-stat"><span>Bloqueados</span><strong>${list.filter(p=>p.accountStatus==='suspended').length}</strong></div></section><section class="vp-card vp-section">${list.map(p=>`<div class="vp-row"><div class="vp-avatar">${initials(p.name)}</div><div class="vp-row-main"><strong>${safe(p.name)}</strong><small>${p.subscription?.nextDueDate?`Vence ${fmtDate(p.subscription.nextDueDate)} • ${money(p.subscription.amount)}`:'Cobrança não configurada'}</small></div>${p.subscription?.paymentStatus==='pending'?badge('Pagamento pendente','danger'):p.subscription?.nextDueDate?badge('Em dia','ok'):badge('Configurar','warn')}<button class="vp-btn ghost" data-admin-manage="${p.id}">Gerenciar</button></div>`).join('')}</section>`}

function showModal(html){let el=document.getElementById('vpModal');if(el)el.remove();el=document.createElement('div');el.id='vpModal';el.className='vp-modal-bg';el.innerHTML=`<div class="vp-modal">${html}</div>`;document.body.appendChild(el);el.onclick=e=>{if(e.target===el)el.remove()};return el}
function adminManageModal(id){const p=(adminData.personals||[]).find(x=>x.id===id);if(!p)return;const m=showModal(`<div class="vp-page-head"><div><h2>${safe(p.name)}</h2><p>${safe(p.email)} • ${p.athleteCount} aluno(s)</p></div><button class="vp-btn ghost" id="closeModal">×</button></div><div class="vp-grid two"><div class="vp-card compact"><h3>Acesso</h3><p>Status atual: ${safe(p.accountStatus)}</p><div class="vp-actions">${p.accountStatus==='pending'?`<button class="vp-btn ok" data-mstatus="approve">Aprovar</button>`:p.accountStatus==='suspended'?`<button class="vp-btn ok" data-mstatus="reactivate">Reativar</button>`:`<button class="vp-btn danger" data-mstatus="suspend">Bloquear personal + alunos</button>`}</div></div><form class="vp-card compact" id="adminBillingForm"><h3>Cobrança do personal</h3><div class="vp-field"><label>Valor</label><input name="amount" type="number" step="0.01" value="${p.subscription?.amount??''}"></div><div class="vp-field" style="margin-top:7px"><label>Vencimento</label><input name="dueDate" type="date" value="${safe(p.subscription?.nextDueDate||'')}" required></div><div class="vp-field" style="margin-top:7px"><label>Observação</label><input name="notes" value="${safe(p.subscription?.notes||'')}"></div><button class="vp-btn primary" style="margin-top:8px">Salvar</button></form></div><div class="vp-actions" style="margin-top:10px"><button class="vp-btn ok" id="adminPaid">Marcar pagamento recebido</button><button class="vp-btn danger" id="adminPending">Marcar pagamento pendente</button></div>`);m.querySelector('#closeModal').onclick=()=>m.remove();m.querySelectorAll('[data-mstatus]').forEach(b=>b.onclick=async()=>{await adminSetStatus(id,b.dataset.mstatus);m.remove()});m.querySelector('#adminBillingForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{await adminApi('billing_config',{method:'POST',body:{personalId:id,amount:fd.get('amount'),dueDate:fd.get('dueDate'),notes:fd.get('notes')}});await loadAdmin();toast('Cobrança salva.');m.remove();render()}catch(err){toast(err.message)}};m.querySelector('#adminPaid').onclick=()=>adminBillingMark(id,'paid',m);m.querySelector('#adminPending').onclick=()=>adminBillingMark(id,'pending',m)}
async function adminBillingMark(id,status,m){try{await adminApi('billing_mark',{method:'POST',body:{personalId:id,status}});await loadAdmin();toast(status==='paid'?'Pagamento registrado.':'Pagamento marcado como pendente.');m?.remove();render()}catch(e){toast(e.message)}}
async function adminSetStatus(id,mode){try{if(mode==='suspend'&&!confirm('Bloquear este personal e todos os alunos ativos vinculados a ele?'))return;await adminApi('set_status',{method:'POST',body:{personalId:id,mode}});await loadAdmin();toast(mode==='approve'?'Personal aprovado.':mode==='suspend'?'Personal e alunos bloqueados.':'Personal reativado.');render()}catch(e){toast(e.message)}}

function bindCommon(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=async()=>{selected=null;selectedOps=null;view=b.dataset.view;if(me.role==='admin'&&!adminData.personals?.length)await loadAdmin();render()});document.getElementById('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);try{const d=await authApi('profile',{method:'POST',body:{name:fd.get('name'),email:fd.get('email')}});me={...me,...d.user};toast('Cadastro atualizado.');render()}catch(err){toast(err.message)}});document.getElementById('passwordForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);try{const d=await authApi('change_password',{method:'POST',body:{currentPassword:fd.get('current'),newPassword:fd.get('next')}});token=d.token;localStorage.setItem(TOKEN_KEY,token);me.mustChangePassword=false;toast('Senha alterada.');render()}catch(err){toast(err.message)}});document.getElementById('logoutBtn')?.addEventListener('click',async()=>{try{await authApi('logout',{method:'POST'})}catch{}localStorage.removeItem(TOKEN_KEY);token='';me=null;renderAuth()})}
function bindPersonal(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openClient(b.dataset.open,b.dataset.tabTarget||'summary'));document.getElementById('refreshPersonal')?.addEventListener('click',async()=>{await loadPersonal();toast('Dados atualizados.');render()});document.getElementById('claimBtn')?.addEventListener('click',()=>{const m=showModal(`<h2>Vincular aluno</h2><p>Digite o código ID enviado pelo aluno.</p><form id="claimForm"><div class="vp-field"><label>Código</label><input name="code" placeholder="VF-XXXX-XXXX-XXXX" required></div><button class="vp-btn primary" style="margin-top:10px">Vincular</button></form>`);m.querySelector('#claimForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{await vfApi('personal_claim',{method:'POST',body:{code:String(fd.get('code')).toUpperCase()}});await loadPersonal();m.remove();toast('Aluno vinculado.');render()}catch(err){toast(err.message)}}});
  const bf=document.getElementById('brandForm');if(bf){bf.oninput=()=>{const fd=new FormData(bf),p=document.getElementById('brandPreview');if(p){p.style.setProperty('--preview-bg',fd.get('backgroundColor'));p.style.setProperty('--preview-surface',fd.get('surfaceColor'));p.style.setProperty('--preview-primary',fd.get('primaryColor'));p.style.setProperty('--preview-text',fd.get('textColor'));document.getElementById('previewName').textContent=fd.get('systemName')||'Vaz Fitness'}};bf.onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{const d=await req('/api/branding',{method:'POST',body:Object.fromEntries(fd.entries())});brand=d.branding;toast('Identidade salva e sincronizada.');render()}catch(err){toast(err.message)}}}
  document.getElementById('backClients')?.addEventListener('click',()=>{selected=null;selectedOps=null;view='students';render()});document.querySelectorAll('[data-client-tab]').forEach(b=>b.onclick=()=>{clientTab=b.dataset.clientTab;render()});document.getElementById('analyzeClient')?.addEventListener('click',analyzeClient);document.getElementById('savePlan')?.addEventListener('click',savePlan);document.getElementById('addDay')?.addEventListener('click',()=>mutatePlan(p=>p.push({id:`vp-${Date.now()}`,type:'strength',name:'Novo treino',day:1,duration:60,status:'pending',exercises:[]})));document.querySelectorAll('[data-remove-day]').forEach(b=>b.onclick=()=>mutatePlan(p=>p.splice(+b.dataset.removeDay,1)));document.querySelectorAll('[data-add-ex]').forEach(b=>b.onclick=()=>mutatePlan(p=>{const d=p[+b.dataset.addEx];d.exercises=d.exercises||[];d.exercises.push({id:`custom-${Date.now()}`,name:'Novo exercício',muscle:'core',sets:3,reps:'8-12',load:0,rest:60})}));document.querySelectorAll('[data-remove-ex]').forEach(b=>b.onclick=()=>{const [di,ei]=b.dataset.removeEx.split(':').map(Number);mutatePlan(p=>p[di].exercises.splice(ei,1))});document.querySelectorAll('[data-access]').forEach(b=>b.onclick=()=>setStudentAccess(b.dataset.access));document.getElementById('startCycle')?.addEventListener('click',startCycle);document.getElementById('suggestPlan')?.addEventListener('click',suggestPlan);document.getElementById('releaseCycle')?.addEventListener('click',releaseCycle);document.getElementById('studentBillingForm')?.addEventListener('submit',saveStudentBilling);document.getElementById('studentPaid')?.addEventListener('click',()=>markStudentBilling('paid'));document.getElementById('studentPending')?.addEventListener('click',()=>markStudentBilling('pending'))
}
function bindAdmin(){document.querySelectorAll('[data-admin-status]').forEach(b=>b.onclick=()=>adminSetStatus(b.dataset.personal,b.dataset.adminStatus));document.querySelectorAll('[data-admin-manage]').forEach(b=>b.onclick=()=>adminManageModal(b.dataset.adminManage))}
async function analyzeClient(){const box=document.getElementById('aiBox');if(!box)return;box.innerHTML='<div><strong>AION analisando…</strong><small>Cruzando treino, evolução e objetivos.</small></div>';const st=selected.state||{};try{const d=await req('/api/aion',{method:'POST',body:{message:'Você está apoiando um personal trainer. Analise a evolução deste aluno, destaques, sinais de atenção e 3 ações práticas para revisar no plano.',context:{profile:st.profile,goals:st.goals,bodyMeasurements:(st.bodyMeasurements||[]).slice(-10),readiness:(st.readinessCheckins||[]).slice(-7),recentStrength:(st.sessions||[]).slice(-8),recentRuns:(st.runSessions||[]).slice(-8),plan:selected.plan?.plan||[]}},auth:false});box.innerHTML=`<div><strong>AION IA</strong><small>${safe(d.message||'Sem análise disponível.').replace(/\n/g,'<br>')}</small></div>`}catch(e){box.innerHTML='<div><strong>AION indisponível</strong><small>Tente novamente em instantes.</small></div>'}}
async function savePlan(){try{const plan=collectPlan(),notes=document.getElementById('planNotes')?.value||'';const d=await vfApi('personal_plan',{method:'POST',body:{athleteId:selected.athlete.id,plan,notes}});selected.plan={...selected.plan,plan,notes,plan_version:d.plan_version};aiDraft=false;toast('Plano salvo e sincronizado.');render()}catch(e){toast(e.message)}}
async function setStudentAccess(mode){try{if(mode==='suspend'&&!confirm('Bloquear o acesso deste aluno?'))return;await vfApi('personal_access',{method:'POST',body:{athleteId:selected.athlete.id,mode}});await openClient(selected.athlete.id,'access');await loadPersonal();toast(mode==='suspend'?'Aluno bloqueado.':mode==='approve'?'Treino liberado.':'Acesso reativado.')}catch(e){toast(e.message)}}
async function startCycle(){try{const days=+document.getElementById('cycleDays').value;await opsApi('cycle',{method:'POST',body:{athleteId:selected.athlete.id,cycleDays:days,mode:'start'}});selectedOps=await opsApi('client',{params:{athleteId:selected.athlete.id}});await loadPersonal();toast('Ciclo iniciado.');render()}catch(e){toast(e.message)}}
async function suggestPlan(){try{toast('AION está montando o próximo ciclo…');const d=await opsApi('suggest_plan',{method:'POST',body:{athleteId:selected.athlete.id}});selected.plan={...(selected.plan||{}),plan:d.plan};aiDraft=true;clientTab='plan';render();toast('Rascunho AION pronto. Revise exercício por exercício.')}catch(e){toast(e.message)}}
async function releaseCycle(){try{const days=+document.getElementById('cycleDays').value;clientTab='plan';render();await new Promise(r=>setTimeout(r,0));await savePlan();await opsApi('cycle',{method:'POST',body:{athleteId:selected.athlete.id,cycleDays:days,mode:'renew'}});if(selected.athlete.status!=='approved')await vfApi('personal_access',{method:'POST',body:{athleteId:selected.athlete.id,mode:'approve'}});await loadPersonal();await openClient(selected.athlete.id,'management');toast('Novo ciclo liberado para o aluno.')}catch(e){toast(e.message)}}
async function saveStudentBilling(e){e.preventDefault();const fd=new FormData(e.target);try{await opsApi('billing_config',{method:'POST',body:{athleteId:selected.athlete.id,amount:fd.get('amount'),dueDate:fd.get('dueDate'),notes:fd.get('notes')}});selectedOps=await opsApi('client',{params:{athleteId:selected.athlete.id}});await loadPersonal();toast('Mensalidade configurada.');render()}catch(err){toast(err.message)}}
async function markStudentBilling(status){try{await opsApi('billing_mark',{method:'POST',body:{athleteId:selected.athlete.id,status}});selectedOps=await opsApi('client',{params:{athleteId:selected.athlete.id}});await loadPersonal();toast(status==='paid'?'Pagamento registrado.':'Mensalidade marcada como pendente.');render()}catch(e){toast(e.message)}}

init();
