const API_BASE=window.VAZ_API_BASE||'';
const TOKEN_KEY='vazPersonal.token';
const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
let token=localStorage.getItem(TOKEN_KEY)||'';
let me=null,clients=[],view='dashboard',selected=null,clientTab='summary',authMode='login',busy=false;

const dayNames=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const goalNames={hypertrophy:'Hipertrofia',weight_loss:'Emagrecimento',recomp:'Recomposição corporal',strength:'Força',conditioning:'Condicionamento','5k':'5 km','10k':'10 km','21k':'Meia maratona','42k':'Maratona'};
const modeNames={hybrid:'Híbrido',strength:'Musculação',run:'Corrida'};
const muscleNames={chest:'Peitoral',back:'Costas',shoulders:'Ombros',quads:'Quadríceps',hamstrings:'Posteriores',glutes:'Glúteos',arms:'Braços',core:'Core',biceps:'Bíceps',triceps:'Tríceps',calves:'Panturrilhas'};
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2600)}
function apiUrl(action,params={}){const u=new URL(`${API_BASE}/api/vf`,location.origin);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>v!=null&&u.searchParams.set(k,v));return u.toString();}
async function api(action,{method='GET',body=null,params=null}={}){
  const headers={'Content-Type':'application/json'};if(token)headers.Authorization=`Bearer ${token}`;
  const r=await fetch(apiUrl(action,params||{}),{method,headers,body:body?JSON.stringify(body):undefined});
  const data=await r.json().catch(()=>({}));
  if(r.status===401&&action!=='login'&&action!=='register'){logout(false);throw new Error('Sua sessão expirou. Entre novamente.');}
  if(!r.ok)throw new Error(data.message||'Não foi possível concluir a operação.');
  return data;
}
function initials(name='Personal'){return name.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
function statusLabel(s){return s==='approved'?'Ativo':s==='suspended'?'Suspenso':'Aguardando liberação'}
function statusClass(s){return ['approved','suspended'].includes(s)?s:'pending'}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'})}
function formatDuration(min){const n=Number(min)||0;return n>=60?`${Math.floor(n/60)}h ${n%60}m`:`${n} min`}
function currentMonthConsistency(state={}){
  const events=Array.isArray(state.calendarEvents)?state.calendarEvents:[];const d=new Date(),prefix=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-`;
  const planned=events.filter(e=>e.kind==='planned'&&e.date?.startsWith(prefix));const done=planned.filter(e=>e.status==='done').length,fail=planned.filter(e=>['missed','skipped','abandoned'].includes(e.status)).length;
  return done+fail?Math.round(done/(done+fail)*100):null;
}
function clientMetrics(data){
  const st=data?.state||{},sessions=Array.isArray(st.sessions)?st.sessions:[],runs=Array.isArray(st.runSessions)?st.runSessions:[],body=Array.isArray(st.bodyMeasurements)?st.bodyMeasurements:[];
  const mins=[...sessions,...runs].reduce((a,s)=>a+(Number(s.duration)||0),0),km=runs.reduce((a,r)=>a+(Number(r.distance)||0),0),weight=body.at(-1)?.weight||st.profile?.weight||null;
  return {sessions:sessions.length,runs:runs.length,minutes:mins,km,weight,consistency:currentMonthConsistency(st)};
}

async function init(){
  if(!token){render();return;}
  try{const data=await api('me');if(data.user?.role!=='personal')throw new Error('Esta conta não é de personal.');me=data.user;await loadClients();render();}
  catch(e){localStorage.removeItem(TOKEN_KEY);token='';me=null;toast(e.message);render();}
}
async function loadClients(){const data=await api('personal_clients');clients=data.clients||[];}
function logout(show=true){localStorage.removeItem(TOKEN_KEY);token='';me=null;clients=[];selected=null;if(show)api('logout',{method:'POST'}).catch(()=>{});render();}

function render(){if(!me)return renderAuth();app.innerHTML=renderShell();bind();}
function renderAuth(){
  const create=authMode==='register';
  app.innerHTML=`<main class="auth-shell"><section class="auth-card"><div class="auth-brand"><div class="mark">VP</div><div><strong>Vaz Personal</strong><small>Gestão conectada ao Vaz Fitness</small></div></div><span class="eyebrow">${create?'CRIAR CONTA':'ACESSO DO PERSONAL'}</span><h1>${create?'Comece sua central.':'Bem-vindo de volta.'}</h1><p>${create?'Sua conta será usada para receber alunos pelo código ID, liberar planos e acompanhar a evolução.':'Entre para gerenciar seus alunos, planos e liberações.'}</p><form class="auth-form" id="authForm">${create?'<input name="name" placeholder="Seu nome" required maxlength="80">':''}<input name="email" type="email" placeholder="E-mail" required><input name="password" type="password" placeholder="Senha • mínimo 8 caracteres" required minlength="8"><button class="btn primary" ${busy?'disabled':''}>${busy?'Aguarde…':create?'Criar conta de personal':'Entrar'}</button></form><div class="auth-switch">${create?'Já possui conta?':'Ainda não possui conta?'} <button class="link-btn" id="authSwitch">${create?'Entrar':'Criar conta'}</button></div></section></main>`;
  document.getElementById('authSwitch').onclick=()=>{authMode=create?'login':'register';render()};
  document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;render();const fd=new FormData(e.target);try{const data=await api(create?'register':'login',{method:'POST',body:create?{role:'personal',name:fd.get('name'),email:fd.get('email'),password:fd.get('password')}:{email:fd.get('email'),password:fd.get('password')}});if(data.user?.role!=='personal')throw new Error('Use uma conta de personal para entrar nesta central.');token=data.token;localStorage.setItem(TOKEN_KEY,token);me=data.user;await loadClients();toast(create?'Conta criada!':'Login realizado.');}catch(err){toast(err.message)}finally{busy=false;render();}};
}
function renderShell(){
  return `<div class="shell"><header class="topbar"><div class="brand"><div class="mark">VP</div><div><strong>Vaz Personal</strong><small>Central do profissional</small></div></div><button class="user-chip" id="logoutBtn"><span>${initials(me.name)}</span><div><strong>${safe(me.name)}</strong><small>Sair</small></div></button></header><div class="layout"><aside class="sidebar"><button class="nav-btn ${view==='dashboard'?'active':''}" data-view="dashboard">⌂ Visão geral</button><button class="nav-btn ${view==='clients'?'active':''}" data-view="clients">◎ Meus alunos</button><div class="side-note">O Vaz Personal controla a liberação do Vaz Fitness. Mudanças de plano e suspensão ficam registradas no histórico do sistema.</div></aside><main class="content" id="content">${selected?renderClient():view==='clients'?renderClientsPage():renderDashboard()}</main></div><nav class="mobile-nav"><button class="${view==='dashboard'&&!selected?'active':''}" data-view="dashboard">Início</button><button class="${view==='clients'||selected?'active':''}" data-view="clients">Alunos</button><button id="mobileLogout">Sair</button></nav></div>`;
}
function statsCounts(){return {total:clients.length,pending:clients.filter(c=>c.status==='pending').length,active:clients.filter(c=>c.status==='approved').length,suspended:clients.filter(c=>c.status==='suspended').length};}
function renderDashboard(){
  const s=statsCounts();return `<section class="hero"><span class="eyebrow">VAZ PERSONAL</span><h1>Seus alunos, treinos e evolução em um só lugar.</h1><p>Receba o código ID do aluno, revise o perfil e o plano gerado, libere o treino e acompanhe os dados enviados pelo Vaz Fitness.</p></section><section class="grid four stats"><div class="stat"><span>Alunos</span><strong>${s.total}</strong></div><div class="stat"><span>Aguardando</span><strong>${s.pending}</strong></div><div class="stat"><span>Ativos</span><strong>${s.active}</strong></div><div class="stat"><span>Suspensos</span><strong>${s.suspended}</strong></div></section><section class="grid two"><div class="card"><div class="card-head"><div><h2>Adicionar aluno</h2><p>Digite o código enviado pelo Vaz Fitness.</p></div></div><form class="claim-row" id="claimForm"><input class="code" name="code" placeholder="VF-XXXX-XXXX-XXXX" autocomplete="off" required><button class="btn primary">Vincular aluno</button></form></div><div class="card"><div class="card-head"><div><h2>Fila de avaliação</h2><p>Perfis que ainda precisam da sua liberação.</p></div><span class="status pending">${s.pending} pendente(s)</span></div>${renderClientList(clients.filter(c=>c.status==='pending').slice(0,4),true)}</div></section><section class="card" style="margin-top:16px"><div class="card-head"><div><h2>Alunos recentes</h2><p>Acesse ficha, plano, evolução e controle de acesso.</p></div><button class="btn ghost small" data-view="clients">Ver todos</button></div>${renderClientList(clients.slice(0,6))}</section>`;
}
function renderClientsPage(){return `<section class="hero"><span class="eyebrow">CARTEIRA DE ALUNOS</span><h1>Gerencie cada acompanhamento.</h1><p>Veja quem está aguardando avaliação, quem está ativo e quem está com acesso suspenso.</p></section><section class="card" style="margin-top:16px"><div class="card-head"><div><h2>Todos os alunos</h2><p>${clients.length} vínculo(s)</p></div></div>${renderClientList(clients)}</section>`;}
function renderClientList(list,compact=false){
  if(!list.length)return `<div class="empty">${compact?'Nenhum aluno aguardando liberação.':'Você ainda não possui alunos vinculados.'}</div>`;
  return `<div class="client-list">${list.map(c=>`<div class="client-row"><div class="client-avatar">${initials(c.name)}</div><div><strong>${safe(c.name)}</strong><small><span class="code">${safe(c.publicCode)}</span>${c.summary?.lastActivity?` • último treino ${fmtDate(c.summary.lastActivity)}`:''}</small></div><span class="status ${statusClass(c.status)}">${statusLabel(c.status)}</span><button class="btn ghost small open-label" data-client="${safe(c.id)}">Abrir</button></div>`).join('')}</div>`;
}
async function openClient(id){try{const data=await api('personal_client',{params:{athleteId:id}});selected=data;clientTab='summary';view='clients';render()}catch(e){toast(e.message)}}
function renderClient(){
  const a=selected.athlete,st=selected.state||{},p=st.profile||{};
  return `<div class="client-head"><div class="client-title"><button class="btn ghost small back-btn" data-back>← Alunos</button><span class="eyebrow">ALUNO • <span class="code">${safe(a.publicCode)}</span></span><h1>${safe(a.name)}</h1><p>${safe(modeNames[p.mode]||'Perfil')} • ${safe(goalNames[p.goal]||p.goal||'Objetivo não informado')}</p></div><div class="client-head-actions"><span class="status ${statusClass(a.status)}">${statusLabel(a.status)}</span></div></div><div class="tabs">${[['summary','Resumo'],['plan','Plano de treino'],['evolution','Evolução'],['access','Acesso']].map(([id,l])=>`<button class="tab ${clientTab===id?'active':''}" data-tab="${id}">${l}</button>`).join('')}</div>${clientTab==='summary'?renderSummaryTab():clientTab==='plan'?renderPlanTab():clientTab==='evolution'?renderEvolutionTab():renderAccessTab()}`;
}
function renderSummaryTab(){
  const st=selected.state||{},p=st.profile||{},m=clientMetrics(selected),sessions=Array.isArray(st.sessions)?st.sessions:[],runs=Array.isArray(st.runSessions)?st.runSessions:[];
  return `<div class="grid two"><section class="card"><div class="card-head"><div><h2>Perfil do aluno</h2><p>Dados enviados pelo Vaz Fitness.</p></div></div><div class="profile-grid">${[['Idade',p.age?`${p.age} anos`:'—'],['Peso',m.weight?`${m.weight} kg`:'—'],['Altura',p.height?`${p.height} cm`:'—'],['Modalidade',modeNames[p.mode]||'—'],['Objetivo',goalNames[p.goal]||p.goal||'—'],['Frequência',p.days?`${p.days} dias/sem`:'—'],['Nível força',levelName(p.strengthLevel||p.level)],['Nível corrida',levelName(p.runningLevel)],['Prioridade',muscleNames[p.priorityMuscle]||p.priorityMuscle||'—']].map(([k,v])=>`<div class="profile-cell"><span>${k}</span><strong>${safe(v)}</strong></div>`).join('')}</div></section><section class="card"><div class="card-head"><div><h2>Métricas gerais</h2><p>Resumo do histórico sincronizado.</p></div></div><div class="metric-grid"><div class="metric"><span>Musculação</span><strong>${m.sessions}</strong><small>sessões</small></div><div class="metric"><span>Corridas</span><strong>${m.runs}</strong><small>${m.km.toFixed(1)} km</small></div><div class="metric"><span>Tempo ativo</span><strong>${formatDuration(m.minutes)}</strong><small>registrado</small></div><div class="metric"><span>Consistência</span><strong>${m.consistency==null?'—':`${m.consistency}%`}</strong><small>mês atual</small></div></div></section></div><section class="grid two" style="margin-top:16px"><div class="card"><div class="card-head"><div><h2>Atividades recentes</h2><p>Últimos registros do aluno.</p></div></div>${recentActivities(sessions,runs)}</div><div class="card"><div class="card-head"><div><h2>AION para o personal</h2><p>Analise histórico, prontidão e objetivos.</p></div><button class="btn dark small" id="analyzeClient">Analisar</button></div><div class="ai-box" id="aiClientBox">Use a AION como apoio para identificar evolução, sinais de atenção e pontos a revisar no plano. A decisão final de liberação e alteração continua com você.</div></div></section>`;
}
function levelName(v){return v==='advanced'?'Avançado':v==='beginner'?'Iniciante':v==='intermediate'?'Intermediário':'—'}
function recentActivities(sessions,runs){const arr=[...sessions.map(x=>({...x,_kind:'Musculação'})),...runs.map(x=>({...x,_kind:'Corrida'}))].sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,8);if(!arr.length)return '<div class="empty">Nenhum treino concluído ainda.</div>';return arr.map(x=>`<div class="activity"><div><strong>${safe(x.name||x._kind)}</strong><small>${x._kind} • ${fmtDate(x.date)}</small></div><div style="text-align:right"><span>${x._kind==='Corrida'?`${Number(x.distance||0).toFixed(1)} km`:`${Number(x.volume||0).toLocaleString('pt-BR')} kg·rep`}</span><small>${x.duration?formatDuration(x.duration):''}</small></div></div>`).join('')}

function renderPlanTab(){
  const plan=Array.isArray(selected.plan?.plan)?selected.plan.plan:[];
  return `<section class="card"><div class="plan-toolbar"><div><h2 style="margin:0">Plano do aluno</h2><p class="subtle">Revise o plano gerado e personalize antes de liberar. Versão ${selected.plan?.plan_version||0}.</p></div><div><button class="btn ghost small" id="addDay">+ Dia</button> <button class="btn primary small" id="savePlan">Salvar plano</button></div></div><div class="plan-days" id="planDays">${plan.map((d,i)=>renderPlanDay(d,i)).join('')||'<div class="empty">Nenhum dia de treino cadastrado. Adicione um dia antes de liberar o aluno.</div>'}</div><label style="display:block;margin-top:13px"><span class="subtle">Orientações gerais do personal</span><textarea id="planNotes" rows="4" placeholder="Ex.: respeitar dor no ombro, priorizar técnica…">${safe(selected.plan?.notes||'')}</textarea></label></section>`;
}
function renderPlanDay(d,i){
  const type=d.type==='run'?'run':'strength';return `<div class="plan-day" data-day-index="${i}" data-id="${safe(d.id||'')}"><div class="day-top"><select data-day="day">${dayNames.map((n,idx)=>`<option value="${idx}" ${Number(d.day)===idx?'selected':''}>${n}</option>`).join('')}</select><input data-day="name" value="${safe(d.name||'Treino')}" placeholder="Nome do treino"><select data-day="type"><option value="strength" ${type==='strength'?'selected':''}>Musculação</option><option value="run" ${type==='run'?'selected':''}>Corrida</option></select><input data-day="duration" type="number" min="0" max="300" value="${Number(d.duration)||60}" title="Duração em minutos"><button class="btn danger small" data-remove-day="${i}">Excluir</button></div>${type==='run'?`<div class="grid two" style="margin-top:10px"><label><span class="subtle">Pace sugerido</span><input data-day="pace" value="${safe(d.pace||'5:30')}"></label><label><span class="subtle">Intensidade</span><select data-day="intensity"><option ${d.intensity==='Leve'?'selected':''}>Leve</option><option ${d.intensity==='Moderado'?'selected':''}>Moderado</option><option ${d.intensity==='Forte'?'selected':''}>Forte</option><option ${d.intensity==='Livre'?'selected':''}>Livre</option></select></label></div>`:`<div class="day-exercises">${(d.exercises||[]).map((e,j)=>renderExerciseEditor(e,i,j)).join('')}<button class="btn ghost small" data-add-exercise="${i}" style="margin-top:9px">+ Exercício</button></div>`}</div>`;
}
function renderExerciseEditor(e,di,ei){return `<div class="exercise-editor" data-exercise data-id="${safe(e.id||'')}" data-icon="${safe(e.icon||'🏋️')}"><input data-ex="name" value="${safe(e.name||'Exercício')}" placeholder="Exercício"><select data-ex="muscle">${Object.entries(muscleNames).map(([v,l])=>`<option value="${v}" ${e.muscle===v?'selected':''}>${l}</option>`).join('')}</select><input data-ex="sets" type="number" min="1" max="10" value="${Number(e.sets)||3}" title="Séries"><input data-ex="reps" value="${safe(e.reps||'8-12')}" title="Repetições"><input data-ex="load" type="number" step="0.5" min="0" value="${Number(e.load)||0}" title="Carga kg"><input data-ex="rest" type="number" min="15" max="600" value="${Number(e.rest)||60}" title="Descanso s"><button class="btn danger small" data-remove-exercise="${di}:${ei}">×</button></div>`}
function collectPlan(){return [...document.querySelectorAll('.plan-day')].map((el,idx)=>{const type=el.querySelector('[data-day="type"]').value;const base={id:el.dataset.id||`vp-${Date.now()}-${idx}`,type,name:el.querySelector('[data-day="name"]').value.trim()||'Treino',day:+el.querySelector('[data-day="day"]').value,duration:+el.querySelector('[data-day="duration"]').value||0,status:'pending'};if(type==='run'){base.pace=el.querySelector('[data-day="pace"]')?.value.trim()||'5:30';base.intensity=el.querySelector('[data-day="intensity"]')?.value||'Leve';return base}base.exercises=[...el.querySelectorAll('[data-exercise]')].map((row,j)=>({id:row.dataset.id||`custom-${Date.now()}-${idx}-${j}`,name:row.querySelector('[data-ex="name"]').value.trim()||'Exercício',muscle:row.querySelector('[data-ex="muscle"]').value,secondary:[],sets:+row.querySelector('[data-ex="sets"]').value||3,reps:row.querySelector('[data-ex="reps"]').value.trim()||'8-12',load:+row.querySelector('[data-ex="load"]').value||0,rest:+row.querySelector('[data-ex="rest"]').value||60,icon:row.dataset.icon||'🏋️',priority:false}));return base})}
function mutatePlan(mutator){const p=JSON.parse(JSON.stringify(selected.plan?.plan||[]));mutator(p);selected.plan={...(selected.plan||{}),plan:p};render()}

function renderEvolutionTab(){
  const st=selected.state||{},m=clientMetrics(selected),body=Array.isArray(st.bodyMeasurements)?st.bodyMeasurements:[],runs=Array.isArray(st.runSessions)?st.runSessions:[],sessions=Array.isArray(st.sessions)?st.sessions:[];
  const weight0=body[0]?.weight||st.profile?.weight||null,weight1=body.at(-1)?.weight||weight0,bestPace=runs.map(r=>paceSec(r.pace)).filter(Boolean).sort((a,b)=>a-b)[0]||null,maxVolume=Math.max(0,...sessions.map(s=>Number(s.volume)||0));
  return `<section class="grid four"><div class="stat"><span>Peso inicial</span><strong>${weight0?`${weight0} kg`:'—'}</strong></div><div class="stat"><span>Peso atual</span><strong>${weight1?`${weight1} kg`:'—'}</strong></div><div class="stat"><span>Melhor pace</span><strong>${bestPace?`${paceText(bestPace)}/km`:'—'}</strong></div><div class="stat"><span>Maior volume</span><strong>${maxVolume?`${Math.round(maxVolume).toLocaleString('pt-BR')}`:'—'}</strong></div></section><section class="grid two" style="margin-top:16px"><div class="card"><div class="card-head"><div><h2>Peso e medidas</h2><p>Últimos registros corporais.</p></div></div>${body.length?body.slice(-8).reverse().map(x=>`<div class="activity"><div><strong>${Number(x.weight).toFixed(1)} kg</strong><small>${safe(x.date)}</small></div><div style="text-align:right"><span>${x.waist?`${x.waist} cm cintura`:''}</span><small>${x.bodyFat?`${x.bodyFat}% gordura`:''}</small></div></div>`).join(''):'<div class="empty">Sem histórico corporal.</div>'}</div><div class="card"><div class="card-head"><div><h2>Resumo de evolução</h2><p>Dados consolidados do Vaz Fitness.</p></div></div><div class="metric-grid"><div class="metric"><span>Treinos</span><strong>${m.sessions+m.runs}</strong></div><div class="metric"><span>Km</span><strong>${m.km.toFixed(1)}</strong></div><div class="metric"><span>Tempo</span><strong>${formatDuration(m.minutes)}</strong></div><div class="metric"><span>Consistência</span><strong>${m.consistency==null?'—':`${m.consistency}%`}</strong></div></div></div></section>`;
}
function paceSec(v){const m=String(v||'').match(/^(\d+):(\d+)$/);return m?+m[1]*60 + +m[2]:null}function paceText(s){return `${Math.floor(s/60)}:${String(Math.round(s%60)).padStart(2,'0')}`}
function renderAccessTab(){
  const a=selected.athlete;return `<section class="card access-panel"><div class="card-head"><div><h2>Controle de acesso</h2><p>O aluno só consegue usar os treinos após sua liberação.</p></div><span class="status ${statusClass(a.status)}">${statusLabel(a.status)}</span></div>${a.status==='pending'?`<div class="success-note"><strong>Cadastro recebido.</strong><br>Revise o perfil e o plano. Quando estiver pronto, libere o treino do aluno.</div><div style="margin-top:14px"><button class="btn success" data-access="approve">✓ Liberar Vaz Fitness</button></div>`:a.status==='suspended'?`<div class="warning"><strong>Acesso suspenso.</strong><br>O Vaz Fitness bloqueia o carregamento do treino deste aluno.</div><div style="margin-top:14px"><button class="btn success" data-access="reactivate">Reativar acesso</button></div>`:`<div class="success-note"><strong>Treino liberado.</strong><br>O aluno está autorizado a acessar o Vaz Fitness e receber suas alterações de plano.</div><div style="margin-top:14px"><button class="btn danger" data-access="suspend">Suspender acesso</button></div>`}<div class="block-preview"><span class="eyebrow">TELA DO ALUNO EM CASO DE SUSPENSÃO</span><h3>Não foi possível entrar</h3><p>Contate seu personal.</p></div></section>`;
}

async function analyzeClient(){const box=document.getElementById('aiClientBox');if(!box)return;box.textContent='AION está analisando os dados do aluno…';try{const st=selected.state||{};const context={profile:st.profile,goals:st.goals,bodyMeasurements:(st.bodyMeasurements||[]).slice(-10),readiness:(st.readinessCheckins||[]).slice(-7),recentStrength:(st.sessions||[]).slice(-8),recentRuns:(st.runSessions||[]).slice(-8),plan:selected.plan?.plan||[]};const r=await fetch(`${API_BASE}/api/aion`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Você está apoiando um personal trainer na revisão de um aluno do Vaz Fitness. Analise evolução, consistência, esforço, prontidão, corrida, musculação e objetivos. Destaque avanços, sinais de atenção e 3 pontos práticos para revisar no plano. Não faça diagnóstico e não invente dados.',context})});const data=await r.json();box.innerHTML=safe(data.message||'Sem análise disponível.').replace(/\n/g,'<br>')}catch{box.textContent='Não foi possível acessar a AION agora.'}}
async function savePlan(){const plan=collectPlan(),notes=document.getElementById('planNotes')?.value||'';try{const data=await api('personal_plan',{method:'POST',body:{athleteId:selected.athlete.id,plan,notes}});selected.plan={...selected.plan,plan,notes,plan_version:data.plan_version};toast('Plano salvo e sincronizado.');render()}catch(e){toast(e.message)}}
async function setAccess(mode){
  let reason='';if(mode==='suspend'){reason=prompt('Motivo da suspensão (opcional):','')||'';if(!confirm('Suspender o acesso deste aluno ao Vaz Fitness?'))return}else if(mode==='approve'&&!confirm('Liberar este aluno para acessar o Vaz Fitness com o plano atual?'))return;else if(mode==='reactivate'&&!confirm('Reativar o acesso deste aluno?'))return;
  try{const data=await api('personal_access',{method:'POST',body:{athleteId:selected.athlete.id,mode,reason}});selected.athlete.status=data.access.status;selected.athlete.suspendedReason=data.access.suspended_reason;await loadClients();toast(mode==='approve'?'Treino liberado.':mode==='suspend'?'Acesso suspenso.':'Acesso reativado.');render()}catch(e){toast(e.message)}

function bind(){
  document.getElementById('logoutBtn')?.addEventListener('click',()=>logout());document.getElementById('mobileLogout')?.addEventListener('click',()=>logout());
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{selected=null;view=b.dataset.view;render()});
  document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>openClient(b.dataset.client));
  document.querySelector('[data-back]')?.addEventListener('click',()=>{selected=null;view='clients';render()});
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{clientTab=b.dataset.tab;render()});
  const claim=document.getElementById('claimForm');if(claim)claim.onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{await api('personal_claim',{method:'POST',body:{code:String(fd.get('code')||'').trim().toUpperCase()}});await loadClients();toast('Aluno vinculado. Revise a ficha antes de liberar.');render()}catch(err){toast(err.message)}};
  document.getElementById('analyzeClient')?.addEventListener('click',analyzeClient);
  document.getElementById('savePlan')?.addEventListener('click',savePlan);
  document.getElementById('addDay')?.addEventListener('click',()=>mutatePlan(p=>p.push({id:`vp-${Date.now()}`,type:'strength',name:'Novo treino',day:1,duration:60,status:'pending',exercises:[]})));
  document.querySelectorAll('[data-remove-day]').forEach(b=>b.onclick=()=>mutatePlan(p=>p.splice(+b.dataset.removeDay,1)));
  document.querySelectorAll('[data-add-exercise]').forEach(b=>b.onclick=()=>mutatePlan(p=>{const d=p[+b.dataset.addExercise];d.exercises=Array.isArray(d.exercises)?d.exercises:[];d.exercises.push({id:`custom-${Date.now()}`,name:'Novo exercício',muscle:'core',secondary:[],sets:3,reps:'8-12',load:0,rest:60,icon:'🏋️',priority:false})}));
  document.querySelectorAll('[data-remove-exercise]').forEach(b=>b.onclick=()=>{const [di,ei]=b.dataset.removeExercise.split(':').map(Number);mutatePlan(p=>p[di].exercises.splice(ei,1))});
  document.querySelectorAll('[data-day="type"]').forEach(s=>s.onchange=()=>{const plan=collectPlan();selected.plan={...selected.plan,plan};render()});
  document.querySelectorAll('[data-access]').forEach(b=>b.onclick=()=>setAccess(b.dataset.access));
}

init();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));