// Vaz Personal v18 — central financeira mensal, recibos e cobrança confirmada.
(()=>{
  const now=new Date();
  const monthKey=(date=now)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;
  let financeMonth=monthKey(),financeStatus='all',financeSearch='',financeData={accounts:[],payments:[]},financeLoadedAt=0,financeLoading=false;
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const monthName=key=>new Date(`${key}-01T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());
  const daysBetween=(a,b)=>Math.round((new Date(`${a}T12:00:00`).getTime()-new Date(`${b}T12:00:00`).getTime())/86400000);
  const accountById=id=>financeData.accounts.find(x=>x.id===id)||(ops.clients||[]).find(x=>x.id===id)||null;
  const paymentsOf=id=>financeData.payments.filter(x=>x.athleteId===id).sort((a,b)=>String(b.dueDate).localeCompare(String(a.dueDate)));
  const paymentFor=(account,key=financeMonth)=>paymentsOf(account.id).find(x=>String(x.dueDate||'').slice(0,7)===key)||null;
  function dueFor(account,key=financeMonth){const payment=paymentFor(account,key);if(payment?.dueDate)return payment.dueDate;const day=Number(account.billing?.billingDay||String(account.billing?.nextDueDate||'').slice(8,10))||1,[year,month]=key.split('-').map(Number),last=new Date(year,month,0).getDate();return `${key}-${String(Math.min(day,last)).padStart(2,'0')}`}
  function financeState(account,key=financeMonth){if(!account.billing?.configured)return'unconfigured';const payment=paymentFor(account,key);if(payment?.status==='paid')return'paid';const due=dueFor(account,key),diff=daysBetween(due,today());if(diff<0)return'overdue';if(diff===0)return'due';if(diff<=7)return'upcoming';return'pending'}
  const stateMeta=state=>({paid:['Pago','ok','✓'],overdue:['Em atraso','danger','!'],due:['Vence hoje','warn','•'],upcoming:['Próximo','info','⌁'],pending:['Pendente','warn','○'],unconfigured:['Sem mensalidade','neutral','+']}[state]||['Pendente','warn','○']);
  function accounts(){return financeData.accounts.length?financeData.accounts:(ops.clients||[]).map(c=>({id:c.id,name:c.name,publicCode:c.publicCode,billing:c.billing||{}}))}
  function visibleAccounts(){const q=financeSearch.trim().toLowerCase();return accounts().filter(c=>{const state=financeState(c);const statusOk=financeStatus==='all'||(financeStatus==='pending'&&['pending','due','upcoming','overdue'].includes(state))||state===financeStatus;const queryOk=!q||String(c.name||'').toLowerCase().includes(q)||String(c.publicCode||'').toLowerCase().includes(q);return statusOk&&queryOk})}
  function metrics(){const all=accounts(),configured=all.filter(x=>x.billing?.configured),states=configured.map(x=>({account:x,state:financeState(x),payment:paymentFor(x)})),expected=configured.reduce((n,x)=>n+(Number(x.billing.amount)||0),0),paid=states.filter(x=>x.state==='paid'),received=paid.reduce((n,x)=>n+(Number(x.payment?.amount??x.account.billing.amount)||0),0),overdue=states.filter(x=>x.state==='overdue'),upcoming=states.filter(x=>['due','upcoming'].includes(x.state));return {expected,received,toReceive:Math.max(0,expected-received),rate:expected?Math.min(100,Math.round(received/expected*100)):0,paidCount:paid.length,pendingCount:Math.max(0,configured.length-paid.length),overdueCount:overdue.length,overdueValue:overdue.reduce((n,x)=>n+(Number(x.account.billing.amount)||0),0),upcomingCount:upcoming.length,unconfigured:all.length-configured.length}}
  async function loadFinance(force=false){if(financeLoading)return;if(!force&&financeLoadedAt&&Date.now()-financeLoadedAt<60000)return;financeLoading=true;try{const data=await opsApi('finance');financeData={accounts:data.accounts||[],payments:data.payments||[]};financeLoadedAt=Date.now()}finally{financeLoading=false}}
  function financeIcon(name){const icons={expected:'◆',received:'✓',receive:'○',overdue:'!',paid:'↗',pending:'⌛',upcoming:'◷',unconfigured:'+'};return icons[name]||'•'}
  function metricCard(kind,label,value,detail='',tone=''){return `<article class="vp-finance-metric ${tone}"><span>${financeIcon(kind)}</span><div><small>${label}</small><strong>${value}</strong>${detail?`<em>${detail}</em>`:''}</div></article>`}
  function renderFinanceCard(account){const state=financeState(account),meta=stateMeta(state),payment=paymentFor(account),due=dueFor(account),amount=Number(payment?.amount??account.billing?.amount)||0,canCharge=account.billing?.configured&&state!=='paid';return `<article class="vp-student-finance-card ${meta[1]}"><header><div class="vp-billing-avatar">${initials(account.name)}</div><div><strong>${safe(account.name)}</strong><small>${safe(account.publicCode||'')}</small></div><span class="vp-finance-status ${meta[1]}">${meta[2]} ${meta[0]}</span></header><div class="vp-student-finance-value"><small>Mensalidade</small><strong>${account.billing?.configured?money(amount):'—'}</strong></div><div class="vp-student-finance-meta"><span><small>Competência</small><b>${monthName(financeMonth)}</b></span><span><small>Vencimento</small><b>${account.billing?.configured?fmtDate(due):'Configurar'}</b></span></div>${account.billing?.notes?`<p class="vp-finance-note">${safe(account.billing.notes)}</p>`:''}<footer>${account.billing?.configured?`<button class="vp-btn ${state==='paid'?'danger':'primary'}" data-finance-mark="${account.id}" data-payment-status="${state==='paid'?'pending':'paid'}">${state==='paid'?'Marcar pendente':'Marcar pago'}</button>`:`<button class="vp-btn primary" data-finance-config="${account.id}">Configurar</button>`}<button class="vp-btn ghost" data-finance-history="${account.id}">Histórico</button>${state==='paid'?`<button class="vp-btn ghost" data-finance-receipt="${safe(payment?.id||'')}" data-athlete="${account.id}">Recibo</button>`:''}${canCharge?`<button class="vp-btn whatsapp" data-finance-whatsapp="${account.id}">WhatsApp</button>`:''}${account.billing?.configured?`<button class="vp-icon-edit" data-finance-config="${account.id}" aria-label="Editar mensalidade">✎</button>`:''}</footer></article>`}
  renderBilling=function(){const m=metrics(),list=visibleAccounts();return `${pageHead('Financeiro',monthName(financeMonth))}<section class="vp-finance-dashboard"><div class="vp-finance-progress-card"><div class="vp-finance-ring" style="--finance-rate:${m.rate*3.6}deg"><div><strong>${m.rate}%</strong><small>recebido</small></div></div><div><span>Total mensal previsto</span><strong>${money(m.expected)}</strong><small>${m.paidCount} de ${m.paidCount+m.pendingCount} pagamentos</small></div></div><div class="vp-finance-metric-grid">${metricCard('received','Total recebido',money(m.received),'no mês','ok')}${metricCard('receive','Total a receber',money(m.toReceive),`${m.pendingCount} pendente(s)`,'warn')}${metricCard('overdue','Em atraso',money(m.overdueValue),`${m.overdueCount} aluno(s)`,'danger')}${metricCard('paid','Pagamentos realizados',String(m.paidCount),'no mês','ok')}${metricCard('pending','Pagamentos pendentes',String(m.pendingCount),'no mês','warn')}${metricCard('upcoming','Próximos vencimentos',String(m.upcomingCount),'até 7 dias','info')}${metricCard('unconfigured','Sem mensalidade configurada',String(m.unconfigured),'aluno(s)','neutral')}</div></section><section class="vp-card vp-finance-controls"><div class="vp-finance-month"><button data-month-step="-1" aria-label="Mês anterior">‹</button><input type="month" id="financeMonth" value="${financeMonth}"><button data-month-step="1" aria-label="Próximo mês">›</button></div><div class="vp-billing-search"><span>⌕</span><input id="financeSearch" value="${safe(financeSearch)}" placeholder="Buscar aluno"></div><select id="financeStatus" aria-label="Filtrar situação"><option value="all">Todas as situações</option><option value="paid" ${financeStatus==='paid'?'selected':''}>Pagamentos realizados</option><option value="pending" ${financeStatus==='pending'?'selected':''}>Pagamentos pendentes</option><option value="overdue" ${financeStatus==='overdue'?'selected':''}>Em atraso</option><option value="upcoming" ${financeStatus==='upcoming'?'selected':''}>Próximos vencimentos</option><option value="unconfigured" ${financeStatus==='unconfigured'?'selected':''}>Sem mensalidade</option></select><button class="vp-btn dark" id="exportFinanceV18">⇩ Exportar</button></section>${financeLoading?'<div class="vp-billing-loading"><span></span> Atualizando financeiro…</div>':''}<section class="vp-student-finance-grid">${list.length?list.map(renderFinanceCard).join(''):'<div class="vp-card vp-empty">Nenhum aluno encontrado neste filtro.</div>'}</section>`};

  function download(name,type,content){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
  function exportFinanceV18(){const rows=[['Aluno','Código','Competência','Vencimento','Valor','Situação','Pago em','Observações'],...visibleAccounts().map(account=>{const payment=paymentFor(account),state=financeState(account);return [account.name,account.publicCode||'',financeMonth,account.billing?.configured?dueFor(account):'',account.billing?.configured?Number(payment?.amount??account.billing.amount??0).toFixed(2):'',stateMeta(state)[0],payment?.paidAt?new Date(payment.paidAt).toLocaleString('pt-BR'):'',payment?.notes||account.billing?.notes||'']})];const csv='\ufeff'+rows.map(row=>row.map(value=>`"${String(value??'').replace(/"/g,'""')}"`).join(';')).join('\n');download(`vaz-personal-financeiro-${financeMonth}.csv`,'text/csv;charset=utf-8',csv);toast('Controle financeiro exportado.')}
  async function refreshFinance(message){await loadPersonal();financeLoadedAt=0;await loadFinance(true);toast(message);render()}
  async function updatePayment(account,status){const due=dueFor(account);if(status==='pending'&&!confirm(`Marcar a mensalidade de ${account.name} como pendente novamente?`))return;const button=document.querySelector(`[data-finance-mark="${account.id}"]`);if(button){button.disabled=true;button.textContent='Salvando…'}try{await opsApi('payment_update',{method:'POST',body:{athleteId:account.id,dueDate:due,status}});await refreshFinance(status==='paid'?'Pagamento registrado.':'Pagamento marcado como pendente.')}catch(error){if(button)button.disabled=false;toast(error.message)}}
  function openConfig(account){const billing=account.billing||{},due=billing.nextDueDate||dueFor(account);const modal=showModal(`<div class="vp-page-head"><div><span class="eyebrow">MENSALIDADE</span><h2>${safe(account.name)}</h2></div><button class="vp-btn ghost" data-close>×</button></div><form id="financeConfigForm"><div class="vp-form-grid"><div class="vp-field"><label>Valor mensal</label><input name="amount" type="number" min="0" step="0.01" value="${billing.amount??''}" required></div><div class="vp-field"><label>Próximo vencimento</label><input name="dueDate" type="date" value="${safe(due)}" required></div><div class="vp-field"><label>WhatsApp do aluno</label><input name="contactPhone" inputmode="tel" value="${safe(billing.contactPhone||'')}" placeholder="(41) 99999-9999"></div></div><div class="vp-field vp-field-space"><label>Observações</label><textarea name="notes" rows="3" maxlength="500" placeholder="Forma de pagamento, desconto ou observação">${safe(billing.notes||'')}</textarea></div><div class="vp-modal-actions"><button type="button" class="vp-btn ghost" data-close>Cancelar</button><button class="vp-btn primary">Salvar mensalidade</button></div></form>`);modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());modal.querySelector('#financeConfigForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,fd=new FormData(form),button=form.querySelector('button[type="submit"],button:not([type])');button.disabled=true;button.textContent='Salvando…';try{await opsApi('billing_config',{method:'POST',body:{athleteId:account.id,amount:fd.get('amount'),dueDate:fd.get('dueDate'),contactPhone:fd.get('contactPhone'),notes:fd.get('notes')}});modal.remove();await refreshFinance('Mensalidade configurada.')}catch(error){button.disabled=false;button.textContent='Salvar mensalidade';toast(error.message)}}}
  function normalizePayment(raw={}){return {id:raw.id,athleteId:raw.athleteId||selected?.athlete?.id,dueDate:raw.dueDate||String(raw.due_date||'').slice(0,10),amount:raw.amount,status:raw.status,paidAt:raw.paidAt||raw.paid_at,notes:raw.notes||''}}
  function receiptText(account,payment){const number=String(payment.id||`${account.id}-${payment.dueDate}`).replace(/[^a-z0-9]/gi,'').slice(-10).toUpperCase();return `RECIBO Nº ${number}\n\nRecebemos de ${account.name} o valor de ${money(payment.amount??account.billing?.amount??0)}, referente à mensalidade com vencimento em ${fmtDate(payment.dueDate)}.\n\nPagamento registrado em ${payment.paidAt?new Date(payment.paidAt).toLocaleString('pt-BR'):new Date().toLocaleString('pt-BR')}.\n\nPersonal: ${me.name}\nCódigo: ${me.publicCode||''}\nEmitido em: ${new Date().toLocaleString('pt-BR')}`}
  function receiptDocument(account,payment){const text=receiptText(account,payment),lines=text.split('\n');return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Recibo - ${safe(account.name)}</title><style>body{font-family:Arial,sans-serif;background:#f4f4f4;padding:30px;color:#202020}.receipt{max-width:620px;margin:auto;background:#fff;border:1px solid #ddd;border-radius:22px;padding:34px;box-shadow:0 18px 50px #0001}.mark{width:54px;height:54px;border-radius:17px;background:#f5c400;display:grid;place-items:center;font-weight:900}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #f5c400;padding-bottom:20px;margin-bottom:26px}h1{font-size:24px;margin:0}.line{margin:14px 0;line-height:1.6}.sign{margin-top:52px;border-top:1px solid #555;padding-top:8px;width:260px}@media print{body{background:#fff;padding:0}.receipt{box-shadow:none;border:0}}</style></head><body><main class="receipt"><div class="head"><div><h1>Recibo de mensalidade</h1><small>Vaz Personal</small></div><div class="mark">R$</div></div>${lines.map(line=>line?`<div class="line">${safe(line)}</div>`:'<br>').join('')}<div class="sign">${safe(me.name)}<br><small>Personal responsável</small></div></main></body></html>`}
  async function shareReceipt(account,payment){const text=receiptText(account,payment);try{if(navigator.share)await navigator.share({title:`Recibo - ${account.name}`,text});else{await navigator.clipboard.writeText(text);toast('Recibo copiado para compartilhar.')}}catch(error){if(error?.name!=='AbortError')toast('Não foi possível compartilhar o recibo.')}}
  function openReceipt(account,payment){if(!payment)return toast('Pagamento não encontrado.');const text=receiptText(account,payment),modal=showModal(`<div class="vp-page-head"><div><span class="eyebrow">COMPROVANTE</span><h2>Recibo de mensalidade</h2></div><button class="vp-btn ghost" data-close>×</button></div><div class="vp-receipt-preview">${text.split('\n').map(line=>line?`<p>${safe(line)}</p>`:'<br>').join('')}</div><div class="vp-modal-actions"><button class="vp-btn ghost" id="shareReceiptV18">Compartilhar</button><button class="vp-btn primary" id="printReceiptV18">Imprimir / salvar PDF</button></div>`);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.querySelector('#shareReceiptV18').onclick=()=>shareReceipt(account,payment);modal.querySelector('#printReceiptV18').onclick=()=>{const html=receiptDocument(account,payment),win=window.open('','_blank');if(win){win.document.write(html);win.document.close();setTimeout(()=>win.print(),250)}else download(`recibo-${account.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${payment.dueDate}.html`,'text/html;charset=utf-8',html)}}
  function openHistoryV18(account){const payments=paymentsOf(account.id),modal=showModal(`<div class="vp-page-head"><div><span class="eyebrow">HISTÓRICO</span><h2>${safe(account.name)}</h2></div><button class="vp-btn ghost" data-close>×</button></div><div class="vp-payment-history">${payments.length?payments.map(payment=>{const meta=stateMeta(payment.status==='paid'?'paid':String(payment.dueDate)<today()?'overdue':'pending');return `<article><span class="vp-finance-status ${meta[1]}">${meta[2]}</span><div><strong>${monthName(String(payment.dueDate).slice(0,7))}</strong><small>Vencimento ${fmtDate(payment.dueDate)}${payment.paidAt?` • pago ${new Date(payment.paidAt).toLocaleDateString('pt-BR')}`:''}</small>${payment.notes?`<em>${safe(payment.notes)}</em>`:''}</div><b>${money(payment.amount??account.billing?.amount??0)}</b>${payment.status==='paid'?`<button class="vp-btn ghost compact" data-history-receipt="${safe(payment.id)}">Recibo</button>`:''}</article>`}).join(''):'<div class="vp-empty">Nenhum pagamento registrado.</div>'}</div><div class="vp-modal-actions"><button class="vp-btn ghost" id="editFinanceFromHistory">Editar mensalidade</button></div>`);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.querySelector('#editFinanceFromHistory').onclick=()=>{modal.remove();openConfig(account)};modal.querySelectorAll('[data-history-receipt]').forEach(button=>button.onclick=()=>openReceipt(account,payments.find(x=>x.id===button.dataset.historyReceipt)))}
  function whatsappNumber(value){let digits=String(value||'').replace(/\D/g,'');if(digits.length===10||digits.length===11)digits=`55${digits}`;return digits}
  function openWhatsApp(account){const due=dueFor(account),defaultMessage=`Olá, ${account.name}! Passando para lembrar que a mensalidade de ${monthName(financeMonth)}, no valor de ${money(account.billing?.amount||0)}, está pendente. O vencimento é ${fmtDate(due)}. Se já realizou o pagamento, por favor desconsidere. — ${me.name}`;const modal=showModal(`<div class="vp-page-head"><div><span class="eyebrow">LEMBRETE</span><h2>Cobrança pelo WhatsApp</h2><p>A mensagem só será aberta após sua confirmação.</p></div><button class="vp-btn ghost" data-close>×</button></div><form id="whatsappReminderForm"><div class="vp-field"><label>WhatsApp do aluno</label><input name="phone" inputmode="tel" value="${safe(account.billing?.contactPhone||'')}" placeholder="(41) 99999-9999" required></div><div class="vp-field vp-field-space"><label>Mensagem</label><textarea name="message" rows="7" maxlength="1000" required>${safe(defaultMessage)}</textarea></div><div class="vp-confirm-note">✓ Nenhuma mensagem será enviada automaticamente.</div><div class="vp-modal-actions"><button type="button" class="vp-btn ghost" data-close>Cancelar</button><button class="vp-btn whatsapp">Confirmar e abrir WhatsApp</button></div></form>`);modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());modal.querySelector('#whatsappReminderForm').onsubmit=event=>{event.preventDefault();const fd=new FormData(event.currentTarget),phone=whatsappNumber(fd.get('phone')),message=String(fd.get('message')||'');if(phone.length<12){toast('Informe um WhatsApp válido com DDD.');return}if(!confirm(`Abrir o WhatsApp para ${account.name}? A mensagem ficará pronta para você revisar e enviar.`))return;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`,'_blank','noopener');modal.remove()}}
  function shiftMonth(step){const [year,month]=financeMonth.split('-').map(Number),date=new Date(year,month-1+step,1);financeMonth=monthKey(date);render()}

  const previousManagement=renderClientManagement;
  renderClientManagement=function(){let html=previousManagement();html=html.replace('placeholder="Opcional"','min="0" required placeholder="0,00"');if(!html.includes('name="contactPhone"'))html=html.replace('<div class="vp-field" style="margin-top:8px"><label>Observação</label>',`<div class="vp-field" style="margin-top:8px"><label>WhatsApp do aluno</label><input name="contactPhone" inputmode="tel" value="${safe(selectedOps?.billing?.contactPhone||'')}" placeholder="(41) 99999-9999"></div><div class="vp-field" style="margin-top:8px"><label>Observação</label>`);return html};
  saveStudentBilling=async function(event){event.preventDefault();const fd=new FormData(event.target);try{await opsApi('billing_config',{method:'POST',body:{athleteId:selected.athlete.id,amount:fd.get('amount'),dueDate:fd.get('dueDate'),contactPhone:fd.get('contactPhone'),notes:fd.get('notes')}});selectedOps=await opsApi('client',{params:{athleteId:selected.athlete.id}});financeLoadedAt=0;await loadPersonal();toast('Mensalidade configurada.');render()}catch(error){toast(error.message)}};

  const previousBindPersonal=bindPersonal;
  bindPersonal=function(){previousBindPersonal();if(view!=='billing'||selected)return;document.querySelectorAll('[data-month-step]').forEach(button=>button.onclick=()=>shiftMonth(Number(button.dataset.monthStep)));const month=document.getElementById('financeMonth');if(month)month.onchange=()=>{if(/^\d{4}-\d{2}$/.test(month.value)){financeMonth=month.value;render()}};const search=document.getElementById('financeSearch');if(search)search.oninput=()=>{financeSearch=search.value;render()};const status=document.getElementById('financeStatus');if(status)status.onchange=()=>{financeStatus=status.value;render()};document.getElementById('exportFinanceV18')?.addEventListener('click',exportFinanceV18);document.querySelectorAll('[data-finance-mark]').forEach(button=>button.onclick=()=>{const account=accountById(button.dataset.financeMark);if(account)updatePayment(account,button.dataset.paymentStatus)});document.querySelectorAll('[data-finance-config]').forEach(button=>button.onclick=()=>{const account=accountById(button.dataset.financeConfig);if(account)openConfig(account)});document.querySelectorAll('[data-finance-history]').forEach(button=>button.onclick=()=>{const account=accountById(button.dataset.financeHistory);if(account)openHistoryV18(account)});document.querySelectorAll('[data-finance-receipt]').forEach(button=>button.onclick=()=>{const account=accountById(button.dataset.athlete),payment=paymentFor(account);openReceipt(account,payment)});document.querySelectorAll('[data-finance-whatsapp]').forEach(button=>button.onclick=()=>{const account=accountById(button.dataset.financeWhatsapp);if(account)openWhatsApp(account)});if(!financeLoadedAt&&!financeLoading){loadFinance(true).then(()=>{if(view==='billing'&&!selected)render()}).catch(error=>toast(error.message))}};
  const previousBindWithReceipts=bindPersonal;
  bindPersonal=function(){previousBindWithReceipts();document.querySelectorAll('[data-receipt]').forEach(button=>button.onclick=()=>{const account=accountById(selected?.athlete?.id)||{id:selected?.athlete?.id,name:selected?.athlete?.name,billing:selectedOps?.billing||{}},payment=normalizePayment((selectedOps?.payments||[]).find(x=>x.id===button.dataset.receipt));openReceipt(account,payment)})};
  window.__VAZ_FINANCE_V18_TEST__={monthKey,dueFor,financeState,stateMeta,whatsappNumber,metrics,setData:data=>{financeData=data},setMonth:key=>{financeMonth=key}};
})();
